force-app/main/default/objects/Account/recordTypes/VC.recordType-meta.xml
<RecordType>
    <fullName>VC</fullName>
    <active>true</active>
    <label>VC</label>
</RecordType>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <description>The actual amount received from Limited Partners.</description>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Committed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Committed_Amount__c</fullName>
    <description>The total amount that have been pledged or promised by Limited Partners.</description>
    <label>Committed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will be use to link the Commitment with the Fund it was created for</description>
    <label>Fund</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Commitments</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinServ__FinancialAccount__c/recordTypes/Commitment.recordType-meta.xml
<RecordType>
    <fullName>Commitment</fullName>
    <active>true</active>
    <label>Commitment</label>
</RecordType>

force-app/main/default/objects/FinServ__FinancialAccount__c/recordTypes/Fund.recordType-meta.xml
<RecordType>
    <fullName>Fund</fullName>
    <active>true</active>
    <label>Fund</label>
</RecordType>

force-app/main/default/classes/CaptitalCallRecommendationGeneratorTest.cls
@isTest
private class CaptitalCallRecommendationGeneratorTest {
    @testSetup static void setup() {
        // Create common test Account
        Account testacc = new Account();
        testacc.Name = 'VC Funds'; 
        insert testacc;  
        // Create common test Funds
        FinServ__FinancialAccount__c testfundObj = new FinServ__FinancialAccount__c();
        testfundObj.Name = 'CK Large Cap Fund'; 
        testfundObj.FinServ__PrimaryOwner__c = testacc.Id;
        insert testfundObj;  

        // Create common test Commitments
        FinServ__FinancialAccount__c testCommObj = new FinServ__FinancialAccount__c();
        testCommObj.Name = 'Test CK Commitment';
        testCommObj.Fund__c = testfundObj.id; 
        testCommObj.Committed_Amount__c = 200000;
        testCommObj.Amount_Received__c = 100000;
        testCommObj.FinServ__PrimaryOwner__c = testacc.Id;
        insert testCommObj;        
    }

    @isTest 
    static void testNewCapitalCall() {
        List<FinServ__FinancialAccount__c> funds = [SELECT id,
                                                            Name
                                                    FROM FinServ__FinancialAccount__c 
                                                    WHERE Name =: 'CK Large Cap Fund'];
        System.assert(funds.size() > 0);
        List<List<Recommendation>> result = CaptitalCallRecommendationGenerator.getCommitmentsById(funds[0].id);
        System.assert(result.size() > 0);
    }
   
}